name: Stage
description: Build stage progressing or finishing the compilation in a container

inputs:
  finished:
    description: If a previous stage already finished the build, the stage will set all output variables to the input ones and exit
    required: false
  progress-name:
    description: The name of the progress artifact to be used
    required: false
  package:
    description: Package name
    required: true
  use-registry:
    description: If the image should be retrieved from ghcr.io or from an artifact called 'image'
    required: false
  registry-token:
    description: The access token for ghcr.io (required if 'use-registry' is set)
    required: false
  image-tag:
    description: The tag of the container image to use (required if 'use-registry' is set)
    required: false
  arch:
    description: Built arch
    required: false

outputs:
  finished:
    description: If a previous stage already finished the build, the stage will set all output variables to the input ones and exit
  package:
    description: Package name
  use-registry:
    description: If the image should be retrieved from ghcr.io or from an artifact called 'image'
  image-tag:
    description: The tag of the container image to use (required if 'use-registry' is set)

runs:
  using: node16
  main: dist/index.js
