name: Build repo

on:
  push:
    branches: [ "gh-pages", "main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Import GPG key
        if: always() && github.event_name != 'pull_request'
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_SECRET }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Install git
        run: |
          pacman -Syu --noconfirm git
          git clone https://cheetah-aur-bot:${{ secrets.ACCESS_TOKEN }}@github.com/cheetah-aur/packages.git --branch=gh-pages 
          cd packages
          git remote set-url origin https://cheetah-aur-bot:${{ secrets.ACCESS_TOKEN }}@github.com/cheetah-aur/packages.git
          ls -la
          repo-add x86_64/cheetah-aur.db.tar.gz x86_64/*.pkg.tar.xz
          repo-add x86_64-v3/cheetah-aur.db.tar.gz x86_64-v3/*.pkg.tar.xz
          for file in x86_64/*.db*
          do
            gpg --detach-sign --use-agent --default-key "${gpg_key}" --batch --yes "${file}"
          done
          
          for file in x86_64/*.files*
          do
            gpg --detach-sign --use-agent --default-key "${gpg_key}" --batch --yes "${file}"
          done

          for file in x86_64-v3/*.db*
          do
            gpg --detach-sign --use-agent --default-key "${gpg_key}" --batch --yes "${file}"
          done
          
          for file in x86_64-v3/*.files*
          do
            gpg --detach-sign --use-agent --default-key "${gpg_key}" --batch --yes "${file}"
          done
          pwd
          git config --global user.name "Cheetah-aur-bot"
          git config --global user.email "Cheetah-aur@proton.me"
          git add .
          git commit -m "Update repo"
          git push
        env:
          gpg_key: ${{ secrets.GPG_KEY }}
     